### ISSUE TITLE
error: use of undeclared identifier 'opendmarc_policy_fetch_fo' in opendmarc.c

### ISSUE THREAD

**Issue by smwardle** [trusteddomainproject/OpenDMARC#407]
opendmarc fails to build on MacOSX26.5, failing with one error:

opendmarc.c:3257:3: error: use of undeclared identifier
      'opendmarc_policy_fetch_fo'
 3257 |                 opendmarc_policy_fetch_fo(cc->cctx_dmarc, &fo);

It was building prior to May 22nd.
Apple clang version 21.0.0 (clang-2100.1.1.101)
Target: arm64-apple-darwin25.5.0
Thread model: posix

**Comment by thegushi** [comment]
I'll try to reproduce this tonight.

**Comment by thegushi** [comment]
Hey there,

Okay, thanks for causing me this fun evening.  We now have a self-hosted macos github CI runner to catch compile fails, which was harder than it sounds because there's no native sendmail package in homebrew or anything like that.

The fix for this has been merged into the develop branch, can you confirm it's working sanely?

**Comment by smwardle** [comment]
Thanks. opendmarc builds now.
I'm using macports  which provides libmilter @8.17.1 and lua @5.3.6

make check live-tests all pass but filter-tests all fail.
miltertest is installed from the OpenDKIM development branch and all tests pass when building that.

opendmarc/opendmarc -V
opendmarc: OpenDMARC Filter vrel-opendmarc-1-4-2-240-gc669a0a
	SMFI_VERSION 0x1000001
	libmilter version 1.0.1
	Configured with:  'CC=/usr/bin/clang' 'CPPFLAGS=-I/opt/local/include -DSM_CONF_STDBOOL_H=1' 'LDFLAGS=-L/opt/local/lib -lresolv' 'LT_SYS_LIBRARY_PATH=/opt/local' 'CFLAGS=-pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -arch arm64' '--with-sql-backend' '--with-lua=/opt/local' '--with-milter=/opt/local' '--enable-live-tests' '--enable-filter-tests'

[test-suite.log](https://github.com/user-attachments/files/28663520/test-suite.log)

**Comment by thegushi** [comment]
Thanks for attaching the log -- that pointed us straight at the root cause.

**What was wrong**: `mlfi_eom()` had two oversized stack allocations that overflowed macOS ARM64's default 512KB thread stack (vs. Linux's 8MB). A `unsigned char header[4096]` (MAXHEADER was bumped recently) and a `struct authres ar` (~273KB -- 32 result slots each with two `char[16][257]` arrays) were sitting on the stack. On macOS that triggers `___chkstk_darwin` hitting the guard page, which sends SIGBUS to the filter process. Both are now heap-allocated. Fix is in PR #410, merged to develop.

One filter test (`t-verify-self-spf`) would still fail unless you configure with `--with-spf`, but that's now fixed in #412 so it skips cleanly rather than failing when SPF support isn't compiled in.

We weren't planning to add full macOS CI this week, but here we are -- both OpenDMARC and OpenDKIM now have macOS CI jobs. In CI we build libmilter from the sendmail source tarball since it's not in Homebrew; you're building against MacPorts libmilter which should be fine either way since the fix is entirely in our code.

Can you pull the latest develop and confirm `make check` and the filter tests work for you now?

**Comment by thegushi** [comment]
One more thing while we have you: we ship a systemd unit in `contrib/service/` for Linux deployments. Since you're running this on macOS, do you have a launchd plist for it that you'd be willing to contribute? We'd add it to `contrib/launchd/` alongside the existing init scripts.

**Comment by smwardle** [comment]
Thanks again. I can confirm opendmarc builds and passes all tests as expected now om my macOS system.
Attached the plist I'm using, renamed to keep github happy.

On checking my open dmarc.conf against the sample it seems some spurious spaces have appeared after the hashes on lines 117, 129 and 140. There's also one on line 345 but that's not new.

[local.opendmarc.plist.txt](https://github.com/user-attachments/files/28674260/local.opendmarc.plist.txt)
